-d C:\Code\FPGA_comptaiton\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW2A-18-PBGA484-8
-pn GW2A-LV18PG484C8/I7
-cst C:\Code\FPGA_comptaiton\fpga_project\src\fpga_project.cst
-cfg C:\Code\FPGA_comptaiton\fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
